### ISSUE TITLE
Log entries broken into several lines

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#763] opened 2022-11-25 16:40 UTC
When a log message spans over more than one line, an log entry is created per line, making debugging difficult

**Comment by SanjayVas** [comment] 2022-11-28 18:19
Structured logging should address this.

**Comment by SanjayVas** [comment] 2022-11-28 18:21
Duplicate of #762

**Closed** 2022-11-28 18:20 UTC
Labels: duplicate
