### ISSUE TITLE
SIGBUS from JRE when building //src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools:CreateResource

### ISSUE THREAD

**Issue by dprao88** [world-federation-of-advertisers/cross-media-measurement#884] opened 2023-03-09 17:51 UTC
**Describe the bug**
Deployment is getting failed M4.15

**Component(s) affected**
Kingdom, Duchy, Reporting Server, testing simulators

**Environment**
Prod environment

**Additional context**
Please find the logs

[Deployment_Failed_M4.15_LOGS.txt](https://github.com/world-federation-of-advertisers/cross-media-measurement/files/10934491/Deployment_Failed_M4.15_LOGS.txt)

**Comment by SanjayVas** [comment] 2023-03-09 18:10
The logs appear to be coming from some custom build script that isn't from Halo code. What I'm mainly seeing is a bus error (SIGBUS) from the JRE. This is a build/compilation error and not a deployment error. I've renamed the bug accordingly.

At first glance this doesn't appear to be Halo bug but rather an issue with the build environment (e.g. the machine that the build is being run on). What is the environment you are building on? e.g. OS version, architecture, etc. I assume this was working before and then something changed. Can you identify what that something might be? e.g. works on commit X but fails on commit Y?

**Comment by dprao88** [comment] 2023-03-09 18:55
Hi @SanjayVas, we have an update on this. For the first time it's failed. However, when we run again, those issues disappear. Please find the logs. 
[Deployment_WORKED_M4.15_LOGS.txt](https://github.com/world-federation-of-advertisers/cross-media-measurement/files/10935012/Deployment_WORKED_M4.15_LOGS.txt)

**Comment by SanjayVas** [comment] 2023-03-09 19:01
Closing this as not reproducible, as it appears to be a transient error in the JRE.

**Closed by SanjayVas** 2023-03-09 19:01 UTC
Labels: bug, needs info, triaged

**Comment by SanjayVas** [comment] 2023-03-09 19:07
The flakiness could be due to https://github.com/bazelbuild/rules_jvm_external/issues/745, which is mitigated by updating rules_jvm_external to 5.0+.
