### ISSUE TITLE
Replace deprecated getRuntimePath() by using Runfiles

### ISSUE THREAD

**Issue by renjiezh** [world-federation-of-advertisers/cross-media-measurement#1749] opened 2024-08-11 19:13 UTC
**Describe the bug**
`getRuntimePath()` is deprecated. It should be replaced by using Runfiles.getRuntimePath with Runfiles.preload().

**Steps to reproduce**
N/a

**Component(s) affected**
N/a

**Version**
v0.5.7

**Environment**
N/a

**Additional context**

**Comment by SanjayVas** [comment] 2024-08-12 16:59
Duplicate of #1749

**Closed by SanjayVas** 2024-08-12 16:59 UTC
Labels: duplicate, internal cleanup
