### ISSUE TITLE
Discrepancy in pattern for the event groups. The requisition proto is expecting to use the different pattern.

### ISSUE THREAD

**Issue by dprao88** [world-federation-of-advertisers/cross-media-measurement#1034] opened 2023-05-30 16:07 UTC
**Describe the bug**
EventGroupEntry key format discrepancy ("measurementConsumers/{measurement_consumer}/dataProviders/{data_provider}/eventGroups/{event_group}" vs. "dataProviders/{data_provider}/eventGroups/{event_group}")

Please find the below proto files.
- **requisition_spec.proto** - https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/38e6f0a1801d52b32ddb46f17e02698e0e099407/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L38
- **event_group.proto** - https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/38e6f0a1801d52b32ddb46f17e02698e0e099407/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L33

- Please find the difference in type fields from the above protos. Thank you!
**Steps to reproduce**
The requisition proto is expecting to use this pattern:
 type: “[halo.wfanet.org/EventGroup](http://halo.wfanet.org/EventGroup)”
    pattern: “dataProviders/{data_provider}/eventGroups/{event_group}”

**Component(s) affected**
 Reporting Server

**Version**
7c63b7aa666c256d6304730aad788e18accdffe1

**Environment**
Prod Environment

**Additional context**
Req. spec:
<img width="454" alt="image" src="https://github.com/world-federation-of-advertisers/cross-media-measurement/assets/122367168/6daf1399-e110-46d0-918e-c1f9e9fc78a8">
Event group:
<img width="514" alt="image" src="https://github.com/world-federation-of-advertisers/cross-media-measurement/assets/122367168/40a70e6d-4448-48b2-91c3-c9dccb9101c4">

**Comment by SanjayVas** [comment] 2023-05-30 17:24
The Reporting API and CMMS API have different patterns for EventGroup resource names. This is by design. You can tell which one to use by looking at the resource reference type. If you see `reporting.halo-cmm.org/EventGroup`, then the pattern is `measurementConsumers/{measurement_consumer}/dataProviders/{data_provider}/eventGroups/{event_group}`. If you see `halo.wfanet.org/EventGroup` then it's `dataProviders/{data_provider}/eventGroups/{event_group}`.

**Comment by SanjayVas** [comment] 2023-05-30 17:32
Okay, I think I get what this issue is actually stating. Is it that the `RequisitionSpec`s created by the v1 Reporting system are using that API's pattern instead of the CMMS API's pattern?

**Comment by mariolamassaavedra** [comment] 2023-05-31 08:46
@SanjayVas  that's correct

**Comment by riemanli** [comment] 2023-06-01 16:44
Resolved in #1038

**Closed by riemanli** 2023-06-01 16:44 UTC
Labels: bug, triaged

**Comment by SanjayVas** [comment] 2023-06-01 16:52
Note that this only fixes forward. All v1 Reports and their resulting Measurements created before #1038 are likely invalid.
