### ISSUE TITLE
Doing a certificate rotation results in "Invalid Certificate" message

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#797] opened 2023-01-05 16:58 UTC
**Describe the bug**
We were able to rotate the MC certificate/keys successfully (revoke, add, update keys). We can see the updated values in getconsumer method and were able to create event groups. We also updated the reporting server secrets to have the latest values. However, when creating a report through the reporting server we are getting Certificate is Invalid. From reading the code I assume this probably is due to a wrong value being passed [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b69f180251a484327f7edd2b52932b8cf5dbf519/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L366)  which then results in the error coming back from the [spanner measurement method](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b69f180251a484327f7edd2b52932b8cf5dbf519/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L56) (is the only place I could find the specific error we are getting).

**Steps to reproduce**
1. Add new certificate to an MC entity
2. Revoke old MC certificate 
3. Update MC key
4. Get MC and validate the new values are available in the MC object
5. Create measurement(s) for the MC (we've done it via the reporting server by creating a report)
6. Error appears in the kingdom logs and is returned to the reporting server as a response

**Component(s) affected**
~~Kingdom~~ Reporting server

**Version**
(https://github.com/world-federation-of-advertisers/cross-media-measurement/commit/3426f122b6f5fd3040cc7d4e9469596f993fb8be)

**Environment**
Origin's Dev Environment

**Additional context**
Will capture and provide

**Comment by duliomatos1** [comment] 2023-01-05 21:08
@riemanli assigning to you, since you've last touched the code referenced in the bug.

**Comment by duliomatos1** [comment] 2023-01-05 21:17
@mariolamassaavedra please fill up Additional Context to @riemanli. We can add this issue to the next support call if unresolved till then.

**Comment by tristanvuong2021** [comment] 2023-01-05 21:25
Does the certificate still work now when using the Kingdom API.

**Comment by dprao88** [comment] 2023-01-10 12:42
@tristanvuong2021 Yes. Its working by using Kingdome API.

**Comment by SanjayVas** [comment] 2023-01-11 18:14
> I assume this probably is due to a wrong value being passed [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b69f180251a484327f7edd2b52932b8cf5dbf519/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L366)

Which certificate gets used when creating a measurement from the Reporting server is controlled by the MeasurementConsumerConfig. Did you update that in your `mc-config` secret in the Reporting server?

**Comment by hpmanso** [comment] 2023-01-12 13:59
We have updated the mc-config secret to use the latest certificate ID and DER file. We have also used the latest PEM and KEY to make the request to the Reporting Server. However, the Invalid Certificate message remains as the output.

**Comment by SanjayVas** [comment] 2023-01-17 21:54
I'm attempting to reproduce this on QA. It's a little tricky as we need to keep everything working with the existing keys, so I'm adding a new MC.

**Comment by SanjayVas** [comment] 2023-01-18 02:15
Unable to reproduce on QA.

Steps:
* Create MC with certificate `measurementConsumers/fnh9xT6pBpg/certificates/PgWU0j6pBnY`
* Create new certificate for MC `measurementConsumers/fnh9xT6pBpg/certificates/ScSQwsJwN_Y`
* Update MC public key using new certificate
* Create new event group for MC `dataProviders/QNqyjKAQ5i4/eventGroups/f_eX3hBvqnQ`
* Revoke first MC certificate
* Create measurement using new certificate `measurementConsumers/fnh9xT6pBpg/measurements/ePcsuz1hv6o`

Measurement created using MeasurementSystem tool:

```shell
bazel-bin/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem --kingdom-public-api-target=v2alpha.kingdom.dev.halo-cmm.org:8443 --tls-cert-file src/main/k8s/testing/secretfiles/mc_tls.pem --tls-key-file src/main/k8s/testing/secretfiles/mc_tls.key --cert-collection-file src/main/k8s/testing/secretfiles/kingdom_root.pem measurements --api-key GW8dv8JtJJ8 create --measurement-consumer measurementConsumers/fnh9xT6pBpg --private-key-der-file ~/Private/mc2_2_key.der --measurement-ref-id 'repro world-federation-of-advertisers/cross-media-measurement#797' --reach-and-frequency   --reach-privacy-epsilon=0.0033   --reach-privacy-delta=0.00001   --frequency-privacy-epsilon=0.115   --frequency-privacy-delta=0.00001   --reach-max-frequency=10   --vid-sampling-start=0.16   --vid-sampling-width=0.016667 --data-provider dataProviders/QNqyjKAQ5i4  --event-group dataProviders/QNqyjKAQ5i4/eventGroups/f_eX3hBvqnQ --event-start-time=2022-05-22T01:00:00.000Z   --event-end-time=2022-05-24T05:00:00.000Z
```

Measurement:

```textproto
name: "measurementConsumers/fnh9xT6pBpg/measurements/ePcsuz1hv6o"
measurement_consumer_certificate: "measurementConsumers/fnh9xT6pBpg/certificates/ScSQwsJwN_Y"
measurement_spec {
  data: "\n\351\001\b\001\022\344\001\b\262\310\377\347\005\022\333\001\n\316\001\n=type.googleapis.com/google.crypto.tink.EciesAeadHkdfPublicKey\022\212\001\022D\n\004\b\002\020\003\022:\0228\n0"
  signature: "0E\002!\000\331\307\305\2769\350\277\321\301\306\205\243Gy\326\245?5\0336\005\2767\30591y\357e\270\376/\002 .\2407\324\251\206\374\254\2112\027*\022/\205@(\3158?\fc\367\342\272K\241\002\002\303c\334"
}
data_providers {
  key: "dataProviders/QNqyjKAQ5i4"
  value {
    data_provider_certificate: "dataProviders/QNqyjKAQ5i4/certificates/a5mnb1_vGdM"
    data_provider_public_key {
      data: "\b\001\022\344\001\b\352\321\337/\022\334\001\n\320\001\n=type.googleapis.com/google.crypto.tink.EciesAeadHkdfPublicKey\022\214\001\022D\n\004\b\002\020\003\022:\0228\n0type"
      signature: "0E\002!\000\225\r\350\206i\364\036\v\237\375Z\030\0341K\276\252-\334_66k\340Ns8e\35743\207\002 ln(%\205zs\266}r\212P/\305)\3257f/Uz\315\036\207[\322\031\304\204\ts+"
    }
    encrypted_requisition_spec: "\001\005\367\350\352\004Zoy\362\231\020\020zw\223\252:\263k R\035C\263I\002U\2056\263D\004\274\240\341\020\353\032\371t\326\376\030\334JW\274\333\301\260\034\264\312\003\274H\334;`5\207\034\355\257MPI\2417\356\355\025\265\0022\267\300zG8)\263W\210\302\3206\375*(\344v\367\347\223d\337 \t"
  }
}
protocol_config {
  name: "protocolConfigs/llv2"
  measurement_type: REACH_AND_FREQUENCY
  liquid_legions_v2 {
    sketch_params {
      decay_rate: 7.75
      max_size: 100000
      sampling_indicator_size: 10000000
    }
    data_provider_noise {
      epsilon: 1.0
      delta: 1.0
    }
    elliptic_curve_id: 415
    maximum_frequency: 10
  }
  protocols {
    direct {
    }
  }
  protocols {
    liquid_legions_v2 {
      sketch_params {
        decay_rate: 7.75
        max_size: 100000
        sampling_indicator_size: 10000000
      }
      data_provider_noise {
        epsilon: 1.0
        delta: 1.0
      }
      elliptic_curve_id: 415
      maximum_frequency: 10
    }
  }
}
state: FAILED
measurement_reference_id: "repro world-federation-of-advertisers/cross-media-measurement#797"
failure {
  reason: REQUISITION_REFUSED
  message: "ID of refused Requisition: e151y8KeQMU"
}
```

**Comment by SanjayVas** [comment] 2023-01-18 02:26
Reopening as this was mislabeled as affecting Kingdom where it's actually affecting the Reporting server.

**Comment by SanjayVas** [comment] 2023-01-18 19:28
Unable to reproduce on QA.

Additional steps after https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/797#issuecomment-1386373259:

- Update `certs-and-configs` secret to include new MC root cert in all_root_certs.pem and private key for new MC cert `mc2_cs_private.der`.
- Update `mc-config` secret to add entry for new MC
  ```textproto
  configs {
    key: "measurementConsumers/fnh9xT6pBpg"
    value: {
      api_key: "GW8dv8JtJJ8"
      signing_certificate_name: "measurementConsumers/fnh9xT6pBpg/certificates/ScSQwsJwN_Y"
      signing_private_key_path: "mc2_cs_private.der"
    }
  }
  ```
- Update `config-files` configmap to add entries for new MC in `authority_key_identifier_to_principal_map.textproto` and `encryption_key_pair_config.textproto`.
  ```textproto
  entries {
    authority_key_identifier: "\x53\xEF\x14\xC5\x0A\xEE\xE6\x42\x57\x1D\xD3\xDA\xF1\xED\x69\xBC\x32\xEA\xAB\x35"
    principal_resource_name: "measurementConsumers/fnh9xT6pBpg"
  }
  ```
- Update object configuration for `v1alpha-public-api-server-deployment` with new secret names, also causing it to pick up new version of config-files.
- Create ReportingSet for new MC `measurementConsumers/fnh9xT6pBpg/reportingSets/Z-i6jcZV1Gw`
- Create Report using Reporting CLI tool
  ```shell
  bazel-bin/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting --tls-cert-file ~/Private/mc2_2.crt   --tls-key-file ~/Private/mc2_2_key.pem   --cert-collection-file src/main/k8s/testing/secretfiles/reporting_root.pem   --reporting-server-api-target v1alpha.reporting.dev.halo-cmm.org:8443 reports create --parent=measurementConsumers/fnh9xT6pBpg --event-group-key measurementConsumers/fnh9xT6pBpg/dataProviders/QNqyjKAQ5i4/eventGroups/f_eX3hBvqnQ --interval-start-time=2017-01-15T01:30:15.01Z --interval-end-time=2018-10-27T23:19:12.99Z --interval-start-time=2019-01-19T09:48:35.57Z --interval-end-time=2022-06-13T11:57:54.21Z  --idempotency-key 'repro #797' --metric '
  reach { }
  set_operations {
    unique_name: "operation1"
    set_operation {
      type: UNION
      lhs {
        reporting_set: "measurementConsumers/fnh9xT6pBpg/reportingSets/Z-i6jcZV1Gw"
      }
    }
  }'
  ```
  
Result: Report is created successfully

```textproto
name: "measurementConsumers/fnh9xT6pBpg/reports/TKNWwzmoJs8"
report_idempotency_key: "repro #797"
measurement_consumer: "measurementConsumers/fnh9xT6pBpg"
event_group_universe {
  event_group_entries {
    key: "measurementConsumers/fnh9xT6pBpg/dataProviders/QNqyjKAQ5i4/eventGroups/f_eX3hBvqnQ"
  }
}
time_intervals {
  time_intervals {
    start_time {
      seconds: 1484443815
      nanos: 10000000
    }
    end_time {
      seconds: 1540682352
      nanos: 990000000
    }
  }
  time_intervals {
    start_time {
      seconds: 1547891315
      nanos: 570000000
    }
    end_time {
      seconds: 1655121474
      nanos: 210000000
    }
  }
}
metrics {
  reach {
  }
  set_operations {
    unique_name: "operation1"
    set_operation {
      type: UNION
      lhs {
        reporting_set: "measurementConsumers/fnh9xT6pBpg/reportingSets/Z-i6jcZV1Gw"
      }
      rhs {
      }
    }
  }
}
state: RUNNING
```

**Closed by SanjayVas** 2023-01-18 19:28 UTC
Labels: bug, needs info, triaged
